In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import umap
import torch
import torch.nn as nn
import torch.nn.functional as F
import gc
from tqdm import tqdm

In [3]:
from torch import Tensor

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [5]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.chdir('../IConNet/')
os.getcwd()

'/home/linh/projects/IConNet'

In [6]:
from einops import rearrange, reduce, repeat

In [7]:
dataset_name = 'ravdess'
experiment_prefix = "scb12"
log_dir = f'../{experiment_prefix}_models/analysis/'
data_dir = "../data/data_preprocessed/"
sr = 16000


In [8]:
from omegaconf import OmegaConf as ocf

dataset_config_path = f'config/dataset/{dataset_name}.yaml'
dataset_config = ocf.load(dataset_config_path)
dataset_config['feature_name'] = 'scb_tfidf'
print(dataset_config)


{'name': 'ravdess', 'dataset_class': 'WaveformDataset', 'root': 'ravdess/', 'audio_dir': 'full_release/', 'feature_dir': 'preprocessing/', 'label_name': 'label_emotion_key', 'feature_name': 'scb_tfidf', 'num_classes': 8, 'label_values': ['neu', 'cal', 'hap', 'sad', 'ang', 'fea', 'dis', 'sur'], 'classnames': ['neu', 'cal', 'hap', 'sad', 'ang', 'fea', 'dis', 'sur'], 'target_labels': ['ang', 'neu', 'sad', 'hap']}


In [9]:
from IConNet.trainer.train_torch import get_dataloader

train_loader, test_loader, batch_size = get_dataloader(
    dataset_config, data_dir, batch_size=16)
print(batch_size)

16


In [10]:
from IConNet.trainer.train_torch import Trainer_SCB10
import torch.optim as optim
from pprint import pprint

class Trainer_custom(Trainer_SCB10):
    def __init__(
            self, 
            batch_size, log_dir, experiment_prefix, device,
            eval_ratio: float=0.2,
            gradient_clip_val: float=0,
            accumulate_grad_batches: int=1,

    ):
        super().__init__(
            batch_size, log_dir, experiment_prefix, device,
            eval_ratio, gradient_clip_val, accumulate_grad_batches)

    def setup(self, model, lr=1e-3):
        super().setup(model=None, lr=lr)
        self.model = model
        self.train_losses_detail = []

    def train_step(self):
        device = self.device
        self.model.train()
        loss = torch.tensor(0., dtype=torch.float64, requires_grad=True)
        for batch_idx, (data, target) in enumerate(self.train_loader):
            data = data.to(device)
            target = target.to(device)
            logits = self.model(data)
            loss = loss + F.cross_entropy(logits.squeeze(), target)
            del data, target
            gc.collect()
            torch.cuda.empty_cache()
            if batch_idx % self.accumulate_grad_batches:
                self.optimizer.zero_grad()
                loss.backward()
                self.clip_gradient()
                self.optimizer.step()
                self.current_step += 1
                loss = loss.item()
                self.train_losses.append(loss)
                if batch_idx % self.val_check_batches == 0: 
                    message = self.gen_log_message(
                        batch_idx, loss, loss_detail=None,
                        memory=None
                    )    
                    self.eval_step(loss=loss, message=message)
                loss = torch.tensor(0., dtype=torch.float64, requires_grad=True)
            self._update_progress_bar()
            
    def fit(self, n_epoch=10, lr=None, test_n_epoch=1):
        device = self.device
        self.total_batches = self.train_batches + self.test_batches
        self.pbar_update = 1/self.total_batches
        if lr is not None:
            self.lr = lr
        self.optimizer = optim.RAdam(self.learnable_parameters, lr=self.lr)
        self.scheduler = optim.lr_scheduler.OneCycleLR(
            self.optimizer, max_lr=0.1,
            steps_per_epoch=self.train_batches, 
            epochs=n_epoch)
        self.model.to(device)
        with tqdm(total=n_epoch) as pbar:
            self.pbar = pbar
            for epoch in range(n_epoch):
                self.current_epoch += 1
                self.train_step()
                self.scheduler.step()
                is_test_epoch = (test_n_epoch is not None and test_n_epoch > 0 and epoch % test_n_epoch == 0)   
                if is_test_epoch:
                    metrics, metrics_details, confusion_matrix = self.test_step()
                    pprint(metrics.compute())
                    pprint(metrics_details.compute())
                    pprint(confusion_matrix.compute())
                    self.save()
                
        self.model.to('cpu')  

In [11]:
class TfidfModel(nn.Module):
    def __init__(self, n_input, seq_num_layer, seq_hidden_dim, cls_dim, num_class=4):
        super().__init__()
        self.lstm_blocks = nn.LSTM(
            input_size=n_input, 
            hidden_size=seq_hidden_dim, 
            num_layers=seq_num_layer, 
            batch_first=True
        )
        self.cls_head = nn.Sequential(
            nn.Linear(seq_hidden_dim, cls_dim, bias=False),
            nn.Linear(cls_dim, cls_dim, bias=False),
            nn.PReLU(cls_dim),
            nn.Linear(cls_dim, num_class, bias=False)
        )
        
    def lstm_forward(self, X: Tensor) -> Tensor:
        X, _ = self.lstm_blocks(X.mT)
        return X.mT

    def forward(self, X: Tensor) -> Tensor:
        X = reduce(self.lstm_forward(X), 'b h n -> b h', 'mean')
        X = self.cls_head(X)
        return X

    def predict(self, X: Tensor) -> tuple[Tensor, Tensor]:
        logits = self.forward(X)
        probs = F.softmax(logits, dim=-1)
        preds = probs.argmax(dim=-1)
        return preds, probs

In [12]:
# trainer = Trainer_custom(batch_size=batch_size, log_dir=log_dir, 
#                   experiment_prefix=experiment_prefix, device=device,
#                  accumulate_grad_batches=2, gradient_clip_val=1.)

# trainer.prepare(train_loader=train_loader, 
#                 test_loader=test_loader, 
#                 batch_size=batch_size)

In [13]:
# model = TfidfModel(
#     n_input=3, 
#     seq_num_layer=2, 
#     seq_hidden_dim=128, 
#     cls_dim=128, 
#     num_class=4)

In [14]:
# trainer.setup(model, lr=1e-4)

In [15]:
# trainer.fit(n_epoch=200, test_n_epoch=10)

  1%|▏                                 | 1.0000000000000007/200 [00:09<39:40, 11.96s/it]

Correct: 46/135 (0.3407)
Saved new best test model: ../scb12_models/analysis/model.epoch=1.step=16.test_acc=0.3407.pt
{'acc_unweighted': tensor(0.2962, device='cuda:0'),
 'acc_weighted': tensor(0.3407, device='cuda:0'),
 'f1s_unweighted': tensor(0.1957, device='cuda:0'),
 'f1s_weighted': tensor(0.2238, device='cuda:0'),
 'rocauc': tensor(0.5680, device='cuda:0'),
 'uar': tensor(0.2962, device='cuda:0'),
 'wap': tensor(0.2516, device='cuda:0')}
{'acc_detail': tensor([0.2105, 0.0000, 0.0000, 0.9744], device='cuda:0'),
 'f1s_detail': tensor([0.3077, 0.0000, 0.0000, 0.4750], device='cuda:0'),
 'precision_detail': tensor([0.5714, 0.0000, 0.0000, 0.3140], device='cuda:0'),
 'recall_detail': tensor([0.2105, 0.0000, 0.0000, 0.9744], device='cuda:0'),
 'rocauc_detail': tensor([0.6343, 0.5436, 0.5343, 0.5598], device='cuda:0')}
tensor([[ 8,  0,  0, 30],
        [ 0,  0,  0, 19],
        [ 5,  0,  0, 34],
        [ 1,  0,  0, 38]], device='cuda:0')


  4%|█▍                                  | 8.18749999999996/200 [01:13<38:48, 12.14s/it]

Correct: 49/135 (0.3630)
Saved new best test model: ../scb12_models/analysis/model.epoch=11.step=176.test_acc=0.3630.pt
{'acc_unweighted': tensor(0.3316, device='cuda:0'),
 'acc_weighted': tensor(0.3630, device='cuda:0'),
 'f1s_unweighted': tensor(0.2707, device='cuda:0'),
 'f1s_weighted': tensor(0.2843, device='cuda:0'),
 'rocauc': tensor(0.6429, device='cuda:0'),
 'uar': tensor(0.3316, device='cuda:0'),
 'wap': tensor(0.2658, device='cuda:0')}
{'acc_detail': tensor([0.6316, 0.1053, 0.0000, 0.5897], device='cuda:0'),
 'f1s_detail': tensor([0.5053, 0.1667, 0.0000, 0.4107], device='cuda:0'),
 'precision_detail': tensor([0.4211, 0.4000, 0.0000, 0.3151], device='cuda:0'),
 'recall_detail': tensor([0.6316, 0.1053, 0.0000, 0.5897], device='cuda:0'),
 'rocauc_detail': tensor([0.7314, 0.7482, 0.5206, 0.5716], device='cuda:0')}
tensor([[24,  0,  0, 14],
        [ 2,  2,  0, 15],
        [16,  2,  0, 21],
        [15,  1,  0, 23]], device='cuda:0')


  8%|██▌                               | 15.375000000000163/200 [02:15<37:23, 12.15s/it]

Correct: 48/135 (0.3556)
{'acc_unweighted': tensor(0.3251, device='cuda:0'),
 'acc_weighted': tensor(0.3556, device='cuda:0'),
 'f1s_unweighted': tensor(0.3053, device='cuda:0'),
 'f1s_weighted': tensor(0.3242, device='cuda:0'),
 'rocauc': tensor(0.6432, device='cuda:0'),
 'uar': tensor(0.3251, device='cuda:0'),
 'wap': tensor(0.3499, device='cuda:0')}
{'acc_detail': tensor([0.6053, 0.1053, 0.1282, 0.4615], device='cuda:0'),
 'f1s_detail': tensor([0.5227, 0.1667, 0.1754, 0.3564], device='cuda:0'),
 'precision_detail': tensor([0.4600, 0.4000, 0.2778, 0.2903], device='cuda:0'),
 'recall_detail': tensor([0.6053, 0.1053, 0.1282, 0.4615], device='cuda:0'),
 'rocauc_detail': tensor([0.7320, 0.7464, 0.5275, 0.5670], device='cuda:0')}
tensor([[23,  0,  3, 12],
        [ 2,  2,  1, 14],
        [14,  2,  5, 18],
        [11,  1,  9, 18]], device='cuda:0')


 11%|███▊                              | 22.562499999999808/200 [03:18<35:42, 12.08s/it]

Correct: 40/135 (0.2963)
{'acc_unweighted': tensor(0.2608, device='cuda:0'),
 'acc_weighted': tensor(0.2963, device='cuda:0'),
 'f1s_unweighted': tensor(0.2040, device='cuda:0'),
 'f1s_weighted': tensor(0.2322, device='cuda:0'),
 'rocauc': tensor(0.6392, device='cuda:0'),
 'uar': tensor(0.2608, device='cuda:0'),
 'wap': tensor(0.1998, device='cuda:0')}
{'acc_detail': tensor([0.6842, 0.0000, 0.3333, 0.0256], device='cuda:0'),
 'f1s_detail': tensor([0.4815, 0.0000, 0.2989, 0.0357], device='cuda:0'),
 'precision_detail': tensor([0.3714, 0.0000, 0.2708, 0.0588], device='cuda:0'),
 'recall_detail': tensor([0.6842, 0.0000, 0.3333, 0.0256], device='cuda:0'),
 'rocauc_detail': tensor([0.7303, 0.7387, 0.5190, 0.5689], device='cuda:0')}
tensor([[26,  0,  4,  8],
        [ 3,  0, 14,  2],
        [20,  0, 13,  6],
        [21,  0, 17,  1]], device='cuda:0')


 15%|█████▎                              | 29.7499999999994/200 [04:21<34:24, 12.13s/it]

Correct: 40/135 (0.2963)
{'acc_unweighted': tensor(0.2632, device='cuda:0'),
 'acc_weighted': tensor(0.2963, device='cuda:0'),
 'f1s_unweighted': tensor(0.1372, device='cuda:0'),
 'f1s_weighted': tensor(0.1444, device='cuda:0'),
 'rocauc': tensor(0.6043, device='cuda:0'),
 'uar': tensor(0.2632, device='cuda:0'),
 'wap': tensor(0.1551, device='cuda:0')}
{'acc_detail': tensor([0.0000, 0.0526, 0.0000, 1.0000], device='cuda:0'),
 'f1s_detail': tensor([0.0000, 0.0952, 0.0000, 0.4535], device='cuda:0'),
 'precision_detail': tensor([0.0000, 0.5000, 0.0000, 0.2932], device='cuda:0'),
 'recall_detail': tensor([0.0000, 0.0526, 0.0000, 1.0000], device='cuda:0'),
 'rocauc_detail': tensor([0.7122, 0.7455, 0.4733, 0.4861], device='cuda:0')}
tensor([[ 0,  0,  0, 38],
        [ 0,  1,  0, 18],
        [ 0,  1,  0, 38],
        [ 0,  0,  0, 39]], device='cuda:0')


 18%|██████▍                            | 36.93749999999983/200 [05:24<33:02, 12.16s/it]

Correct: 50/135 (0.3704)
Saved new best test model: ../scb12_models/analysis/model.epoch=51.step=816.test_acc=0.3704.pt
{'acc_unweighted': tensor(0.3249, device='cuda:0'),
 'acc_weighted': tensor(0.3704, device='cuda:0'),
 'f1s_unweighted': tensor(0.2835, device='cuda:0'),
 'f1s_weighted': tensor(0.3240, device='cuda:0'),
 'rocauc': tensor(0.6456, device='cuda:0'),
 'uar': tensor(0.3249, device='cuda:0'),
 'wap': tensor(0.3132, device='cuda:0')}
{'acc_detail': tensor([0.6842, 0.0000, 0.2051, 0.4103], device='cuda:0'),
 'f1s_detail': tensor([0.4906, 0.0000, 0.2581, 0.3855], device='cuda:0'),
 'precision_detail': tensor([0.3824, 0.0000, 0.3478, 0.3636], device='cuda:0'),
 'recall_detail': tensor([0.6842, 0.0000, 0.2051, 0.4103], device='cuda:0'),
 'rocauc_detail': tensor([0.7355, 0.7486, 0.5302, 0.5681], device='cuda:0')}
tensor([[26,  0,  8,  4],
        [ 3,  0,  4, 12],
        [19,  0,  8, 12],
        [20,  0,  3, 16]], device='cuda:0')


 22%|███████▋                           | 44.12500000000065/200 [06:26<31:26, 12.10s/it]

Correct: 48/135 (0.3556)
{'acc_unweighted': tensor(0.3192, device='cuda:0'),
 'acc_weighted': tensor(0.3556, device='cuda:0'),
 'f1s_unweighted': tensor(0.2853, device='cuda:0'),
 'f1s_weighted': tensor(0.3124, device='cuda:0'),
 'rocauc': tensor(0.6489, device='cuda:0'),
 'uar': tensor(0.3192, device='cuda:0'),
 'wap': tensor(0.3395, device='cuda:0')}
{'acc_detail': tensor([0.7368, 0.0526, 0.3077, 0.1795], device='cuda:0'),
 'f1s_detail': tensor([0.5091, 0.0909, 0.3117, 0.2295], device='cuda:0'),
 'precision_detail': tensor([0.3889, 0.3333, 0.3158, 0.3182], device='cuda:0'),
 'recall_detail': tensor([0.7368, 0.0526, 0.3077, 0.1795], device='cuda:0'),
 'rocauc_detail': tensor([0.7360, 0.7536, 0.5254, 0.5807], device='cuda:0')}
tensor([[28,  0,  6,  4],
        [ 3,  1, 10,  5],
        [20,  1, 12,  6],
        [21,  1, 10,  7]], device='cuda:0')


 26%|████████▋                         | 51.312500000001464/200 [07:29<30:00, 12.11s/it]

Correct: 47/135 (0.3481)
{'acc_unweighted': tensor(0.3257, device='cuda:0'),
 'acc_weighted': tensor(0.3481, device='cuda:0'),
 'f1s_unweighted': tensor(0.3030, device='cuda:0'),
 'f1s_weighted': tensor(0.3123, device='cuda:0'),
 'rocauc': tensor(0.6400, device='cuda:0'),
 'uar': tensor(0.3257, device='cuda:0'),
 'wap': tensor(0.3327, device='cuda:0')}
{'acc_detail': tensor([0.6579, 0.1579, 0.1026, 0.3846], device='cuda:0'),
 'f1s_detail': tensor([0.4950, 0.2308, 0.1455, 0.3409], device='cuda:0'),
 'precision_detail': tensor([0.3968, 0.4286, 0.2500, 0.3061], device='cuda:0'),
 'recall_detail': tensor([0.6579, 0.1579, 0.1026, 0.3846], device='cuda:0'),
 'rocauc_detail': tensor([0.7355, 0.7495, 0.5061, 0.5686], device='cuda:0')}
tensor([[25,  0,  6,  7],
        [ 3,  3,  1, 12],
        [18,  2,  4, 15],
        [17,  2,  5, 15]], device='cuda:0')


 29%|██████████▏                        | 58.50000000000228/200 [08:31<28:34, 12.12s/it]

Correct: 48/135 (0.3556)
{'acc_unweighted': tensor(0.3117, device='cuda:0'),
 'acc_weighted': tensor(0.3556, device='cuda:0'),
 'f1s_unweighted': tensor(0.2284, device='cuda:0'),
 'f1s_weighted': tensor(0.2603, device='cuda:0'),
 'rocauc': tensor(0.6520, device='cuda:0'),
 'uar': tensor(0.3117, device='cuda:0'),
 'wap': tensor(0.2065, device='cuda:0')}
{'acc_detail': tensor([0.6316, 0.0000, 0.0000, 0.6154], device='cuda:0'),
 'f1s_detail': tensor([0.5000, 0.0000, 0.0000, 0.4138], device='cuda:0'),
 'precision_detail': tensor([0.4138, 0.0000, 0.0000, 0.3117], device='cuda:0'),
 'recall_detail': tensor([0.6316, 0.0000, 0.0000, 0.6154], device='cuda:0'),
 'rocauc_detail': tensor([0.7401, 0.7686, 0.5288, 0.5705], device='cuda:0')}
tensor([[24,  0,  0, 14],
        [ 2,  0,  0, 17],
        [17,  0,  0, 22],
        [15,  0,  0, 24]], device='cuda:0')


 33%|███████████▍                       | 65.68750000000252/200 [09:35<27:39, 12.35s/it]

Correct: 50/135 (0.3704)
{'acc_unweighted': tensor(0.3251, device='cuda:0'),
 'acc_weighted': tensor(0.3704, device='cuda:0'),
 'f1s_unweighted': tensor(0.2876, device='cuda:0'),
 'f1s_weighted': tensor(0.3285, device='cuda:0'),
 'rocauc': tensor(0.6842, device='cuda:0'),
 'uar': tensor(0.3251, device='cuda:0'),
 'wap': tensor(0.3119, device='cuda:0')}
{'acc_detail': tensor([0.7105, 0.0000, 0.3077, 0.2821], device='cuda:0'),
 'f1s_detail': tensor([0.5243, 0.0000, 0.3478, 0.2785], device='cuda:0'),
 'precision_detail': tensor([0.4154, 0.0000, 0.4000, 0.2750], device='cuda:0'),
 'recall_detail': tensor([0.7105, 0.0000, 0.3077, 0.2821], device='cuda:0'),
 'rocauc_detail': tensor([0.7453, 0.7858, 0.6063, 0.5994], device='cuda:0')}
tensor([[27,  0,  2,  9],
        [ 2,  0,  9,  8],
        [15,  0, 12, 12],
        [21,  0,  7, 11]], device='cuda:0')


 36%|████████████▊                      | 72.87500000000088/200 [10:39<25:52, 12.21s/it]

Correct: 57/135 (0.4222)
Saved new best test model: ../scb12_models/analysis/model.epoch=101.step=1616.test_acc=0.4222.pt
{'acc_unweighted': tensor(0.4163, device='cuda:0'),
 'acc_weighted': tensor(0.4222, device='cuda:0'),
 'f1s_unweighted': tensor(0.4174, device='cuda:0'),
 'f1s_weighted': tensor(0.4191, device='cuda:0'),
 'rocauc': tensor(0.6911, device='cuda:0'),
 'uar': tensor(0.4163, device='cuda:0'),
 'wap': tensor(0.4300, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.3684, 0.3077, 0.4103], device='cuda:0'),
 'f1s_detail': tensor([0.5366, 0.4000, 0.3692, 0.3636], device='cuda:0'),
 'precision_detail': tensor([0.5000, 0.4375, 0.4615, 0.3265], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.3684, 0.3077, 0.4103], device='cuda:0'),
 'rocauc_detail': tensor([0.7469, 0.7768, 0.6007, 0.6402], device='cuda:0')}
tensor([[22,  0,  3, 13],
        [ 2,  7,  4,  6],
        [ 9,  4, 12, 14],
        [11,  5,  7, 16]], device='cuda:0')


 40%|██████████████                     | 80.06249999999925/200 [11:43<24:54, 12.46s/it]

Correct: 54/135 (0.4000)
{'acc_unweighted': tensor(0.3500, device='cuda:0'),
 'acc_weighted': tensor(0.4000, device='cuda:0'),
 'f1s_unweighted': tensor(0.3189, device='cuda:0'),
 'f1s_weighted': tensor(0.3649, device='cuda:0'),
 'rocauc': tensor(0.6903, device='cuda:0'),
 'uar': tensor(0.3500, device='cuda:0'),
 'wap': tensor(0.3401, device='cuda:0')}
{'acc_detail': tensor([0.6053, 0.0000, 0.3333, 0.4615], device='cuda:0'),
 'f1s_detail': tensor([0.4946, 0.0000, 0.3421, 0.4390], device='cuda:0'),
 'precision_detail': tensor([0.4182, 0.0000, 0.3514, 0.4186], device='cuda:0'),
 'recall_detail': tensor([0.6053, 0.0000, 0.3333, 0.4615], device='cuda:0'),
 'rocauc_detail': tensor([0.7583, 0.7477, 0.6149, 0.6405], device='cuda:0')}
tensor([[23,  0,  9,  6],
        [ 5,  0,  8,  6],
        [13,  0, 13, 13],
        [14,  0,  7, 18]], device='cuda:0')


 44%|███████████████▎                   | 87.24999999999761/200 [12:46<22:54, 12.19s/it]

Correct: 54/135 (0.4000)
{'acc_unweighted': tensor(0.3499, device='cuda:0'),
 'acc_weighted': tensor(0.4000, device='cuda:0'),
 'f1s_unweighted': tensor(0.3086, device='cuda:0'),
 'f1s_weighted': tensor(0.3529, device='cuda:0'),
 'rocauc': tensor(0.6861, device='cuda:0'),
 'uar': tensor(0.3499, device='cuda:0'),
 'wap': tensor(0.3515, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.0000, 0.6154, 0.2051], device='cuda:0'),
 'f1s_detail': tensor([0.5057, 0.0000, 0.4528, 0.2759], device='cuda:0'),
 'precision_detail': tensor([0.4490, 0.0000, 0.3582, 0.4211], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.0000, 0.6154, 0.2051], device='cuda:0'),
 'rocauc_detail': tensor([0.7523, 0.7246, 0.6140, 0.6536], device='cuda:0')}
tensor([[22,  0, 11,  5],
        [ 3,  0, 14,  2],
        [11,  0, 24,  4],
        [13,  0, 18,  8]], device='cuda:0')


 47%|████████████████▌                  | 94.43749999999598/200 [13:49<21:23, 12.16s/it]

Correct: 50/135 (0.3704)
{'acc_unweighted': tensor(0.3516, device='cuda:0'),
 'acc_weighted': tensor(0.3704, device='cuda:0'),
 'f1s_unweighted': tensor(0.3053, device='cuda:0'),
 'f1s_weighted': tensor(0.3108, device='cuda:0'),
 'rocauc': tensor(0.6422, device='cuda:0'),
 'uar': tensor(0.3516, device='cuda:0'),
 'wap': tensor(0.4053, device='cuda:0')}
{'acc_detail': tensor([0.6316, 0.2105, 0.0256, 0.5385], device='cuda:0'),
 'f1s_detail': tensor([0.5106, 0.2581, 0.0488, 0.4038], device='cuda:0'),
 'precision_detail': tensor([0.4286, 0.3333, 0.5000, 0.3231], device='cuda:0'),
 'recall_detail': tensor([0.6316, 0.2105, 0.0256, 0.5385], device='cuda:0'),
 'rocauc_detail': tensor([0.7287, 0.7446, 0.5155, 0.5801], device='cuda:0')}
tensor([[24,  1,  0, 13],
        [ 2,  4,  0, 13],
        [16,  4,  1, 18],
        [14,  3,  1, 21]], device='cuda:0')


 51%|█████████████████▎                | 101.62499999999434/200 [14:52<19:58, 12.18s/it]

Correct: 42/135 (0.3111)
{'acc_unweighted': tensor(0.2697, device='cuda:0'),
 'acc_weighted': tensor(0.3111, device='cuda:0'),
 'f1s_unweighted': tensor(0.1506, device='cuda:0'),
 'f1s_weighted': tensor(0.1730, device='cuda:0'),
 'rocauc': tensor(0.5996, device='cuda:0'),
 'uar': tensor(0.2697, device='cuda:0'),
 'wap': tensor(0.3668, device='cuda:0')}
{'acc_detail': tensor([0.0789, 0.0000, 0.0000, 1.0000], device='cuda:0'),
 'f1s_detail': tensor([0.1463, 0.0000, 0.0000, 0.4561], device='cuda:0'),
 'precision_detail': tensor([1.0000, 0.0000, 0.0000, 0.2955], device='cuda:0'),
 'recall_detail': tensor([0.0789, 0.0000, 0.0000, 1.0000], device='cuda:0'),
 'rocauc_detail': tensor([0.7580, 0.7391, 0.4159, 0.4853], device='cuda:0')}
tensor([[ 3,  0,  0, 35],
        [ 0,  0,  0, 19],
        [ 0,  0,  0, 39],
        [ 0,  0,  0, 39]], device='cuda:0')


 54%|██████████████████▍               | 108.81249999999271/200 [15:55<18:52, 12.42s/it]

Correct: 49/135 (0.3630)
{'acc_unweighted': tensor(0.3261, device='cuda:0'),
 'acc_weighted': tensor(0.3630, device='cuda:0'),
 'f1s_unweighted': tensor(0.2474, device='cuda:0'),
 'f1s_weighted': tensor(0.2680, device='cuda:0'),
 'rocauc': tensor(0.6386, device='cuda:0'),
 'uar': tensor(0.3261, device='cuda:0'),
 'wap': tensor(0.2737, device='cuda:0')}
{'acc_detail': tensor([0.8158, 0.0526, 0.0000, 0.4359], device='cuda:0'),
 'f1s_detail': tensor([0.5124, 0.0952, 0.0000, 0.3820], device='cuda:0'),
 'precision_detail': tensor([0.3735, 0.5000, 0.0000, 0.3400], device='cuda:0'),
 'recall_detail': tensor([0.8158, 0.0526, 0.0000, 0.4359], device='cuda:0'),
 'rocauc_detail': tensor([0.7322, 0.7491, 0.5043, 0.5686], device='cuda:0')}
tensor([[31,  0,  0,  7],
        [ 6,  1,  0, 12],
        [24,  1,  0, 14],
        [22,  0,  0, 17]], device='cuda:0')


 58%|███████████████████▋              | 115.99999999999108/200 [16:58<17:07, 12.24s/it]

Correct: 44/135 (0.3259)
{'acc_unweighted': tensor(0.2863, device='cuda:0'),
 'acc_weighted': tensor(0.3259, device='cuda:0'),
 'f1s_unweighted': tensor(0.2122, device='cuda:0'),
 'f1s_weighted': tensor(0.2415, device='cuda:0'),
 'rocauc': tensor(0.6388, device='cuda:0'),
 'uar': tensor(0.2863, device='cuda:0'),
 'wap': tensor(0.1919, device='cuda:0')}
{'acc_detail': tensor([0.6579, 0.0000, 0.0000, 0.4872], device='cuda:0'),
 'f1s_detail': tensor([0.4902, 0.0000, 0.0000, 0.3585], device='cuda:0'),
 'precision_detail': tensor([0.3906, 0.0000, 0.0000, 0.2836], device='cuda:0'),
 'recall_detail': tensor([0.6579, 0.0000, 0.0000, 0.4872], device='cuda:0'),
 'rocauc_detail': tensor([0.7284, 0.7473, 0.5080, 0.5713], device='cuda:0')}
tensor([[25,  0,  1, 12],
        [ 3,  0,  0, 16],
        [19,  0,  0, 20],
        [17,  0,  3, 19]], device='cuda:0')


 62%|████████████████████▉             | 123.18749999998944/200 [18:02<16:03, 12.54s/it]

Correct: 51/135 (0.3778)
{'acc_unweighted': tensor(0.3581, device='cuda:0'),
 'acc_weighted': tensor(0.3778, device='cuda:0'),
 'f1s_unweighted': tensor(0.3462, device='cuda:0'),
 'f1s_weighted': tensor(0.3617, device='cuda:0'),
 'rocauc': tensor(0.6395, device='cuda:0'),
 'uar': tensor(0.3581, device='cuda:0'),
 'wap': tensor(0.3844, device='cuda:0')}
{'acc_detail': tensor([0.6579, 0.2105, 0.2564, 0.3077], device='cuda:0'),
 'f1s_detail': tensor([0.4762, 0.2353, 0.2985, 0.3750], device='cuda:0'),
 'precision_detail': tensor([0.3731, 0.2667, 0.3571, 0.4800], device='cuda:0'),
 'recall_detail': tensor([0.6579, 0.2105, 0.2564, 0.3077], device='cuda:0'),
 'rocauc_detail': tensor([0.7249, 0.7473, 0.5000, 0.5857], device='cuda:0')}
tensor([[25,  2, 10,  1],
        [ 3,  4,  5,  7],
        [19,  5, 10,  5],
        [20,  4,  3, 12]], device='cuda:0')


 65%|██████████████████████▏           | 130.37499999998943/200 [19:05<14:16, 12.30s/it]

Correct: 50/135 (0.3704)
{'acc_unweighted': tensor(0.3445, device='cuda:0'),
 'acc_weighted': tensor(0.3704, device='cuda:0'),
 'f1s_unweighted': tensor(0.3395, device='cuda:0'),
 'f1s_weighted': tensor(0.3593, device='cuda:0'),
 'rocauc': tensor(0.6451, device='cuda:0'),
 'uar': tensor(0.3445, device='cuda:0'),
 'wap': tensor(0.3674, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.1579, 0.3077, 0.3333], device='cuda:0'),
 'f1s_detail': tensor([0.4681, 0.2000, 0.3077, 0.3824], device='cuda:0'),
 'precision_detail': tensor([0.3929, 0.2727, 0.3077, 0.4483], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.1579, 0.3077, 0.3333], device='cuda:0'),
 'rocauc_detail': tensor([0.6975, 0.7450, 0.5248, 0.6130], device='cuda:0')}
tensor([[22,  1, 13,  2],
        [ 2,  3,  6,  8],
        [17,  4, 12,  6],
        [15,  3,  8, 13]], device='cuda:0')


 69%|████████████████████████           | 137.5624999999927/200 [20:08<12:47, 12.29s/it]

Correct: 51/135 (0.3778)
{'acc_unweighted': tensor(0.3704, device='cuda:0'),
 'acc_weighted': tensor(0.3778, device='cuda:0'),
 'f1s_unweighted': tensor(0.3401, device='cuda:0'),
 'f1s_weighted': tensor(0.3370, device='cuda:0'),
 'rocauc': tensor(0.6572, device='cuda:0'),
 'uar': tensor(0.3704, device='cuda:0'),
 'wap': tensor(0.4100, device='cuda:0')}
{'acc_detail': tensor([0.4737, 0.3158, 0.6410, 0.0513], device='cuda:0'),
 'f1s_detail': tensor([0.5000, 0.3529, 0.4167, 0.0909], device='cuda:0'),
 'precision_detail': tensor([0.5294, 0.4000, 0.3086, 0.4000], device='cuda:0'),
 'recall_detail': tensor([0.4737, 0.3158, 0.6410, 0.0513], device='cuda:0'),
 'rocauc_detail': tensor([0.7271, 0.7663, 0.5150, 0.6205], device='cuda:0')}
tensor([[18,  2, 17,  1],
        [ 0,  6, 13,  0],
        [ 8,  4, 25,  2],
        [ 8,  3, 26,  2]], device='cuda:0')


 72%|█████████████████████████▏         | 143.7499999999955/200 [21:01<08:13,  8.77s/it]


In [23]:
from IConNet.nn.model import M11

In [24]:
model_config_path = 'config/model/m10.yaml'
model_config = ocf.load(model_config_path)
model_config

{'name': 'M10', 'description': 'gated residual FirConv', 'fe': {'n_block': 2, 'n_channel': [64, 64], 'kernel_size': [511, 127], 'stride': [2, 8], 'window_k': [2, 9], 'residual_connection_type': 'concat', 'pooling': 'max'}, 'cls': {'n_block': 2, 'n_hidden_dim': [128, 128]}}

In [25]:
model = M11(config=model_config,
           n_input=3, n_output=4)
model

M11(
  (fe_blocks): FeBlocks(
    (blocks): ModuleList(
      (0-1): 2 x FrontEndBlock(
        (block): ModuleDict(
          (layer): FirConvLayer(
            (conv_layer): ResidualConv1d(
              (pad_layer): PadForConv()
              (stride_layer): DownsampleLayer(
                (pad_right): PadForConv()
              )
              (norm_layer): CustomNormLayer(
                (layer): LocalResponseNorm(2, alpha=0.0001, beta=0.75, k=1.0)
              )
              (act): NLReLU()
            )
          )
          (downsample): ResidualConv1d(
            (pad_layer): PadForConv()
            (stride_layer): DownsampleLayer(
              (pad_right): PadForConv()
            )
            (norm_layer): CustomNormLayer(
              (layer): LocalResponseNorm(2, alpha=0.0001, beta=0.75, k=1.0)
            )
            (act): NLReLU()
          )
        )
      )
    )
  )
  (seq_blocks): Seq2SeqBlocks(
    (blocks): LSTM(64, 64, batch_first=True)
  )
  (cls_hea

In [26]:
trainer = Trainer_custom(batch_size=batch_size, log_dir=log_dir, 
                  experiment_prefix=experiment_prefix, device=device,
                 accumulate_grad_batches=2, gradient_clip_val=1.)

trainer.prepare(train_loader=train_loader, 
                test_loader=test_loader, 
                batch_size=batch_size)

In [27]:
trainer.setup(model, lr=1e-4)

In [28]:
trainer.fit(n_epoch=1000, test_n_epoch=10)

  1%|▏                                 | 1.0000000000000007/200 [00:09<41:31, 12.52s/it]

Correct: 39/135 (0.2889)
Saved new best test model: ../scb12_models/analysis/model.epoch=1.step=24.test_acc=0.2889.pt
{'acc_unweighted': tensor(0.2561, device='cuda:0'),
 'acc_weighted': tensor(0.2889, device='cuda:0'),
 'f1s_unweighted': tensor(0.1410, device='cuda:0'),
 'f1s_weighted': tensor(0.1598, device='cuda:0'),
 'rocauc': tensor(0.4718, device='cuda:0'),
 'uar': tensor(0.2561, device='cuda:0'),
 'wap': tensor(0.2030, device='cuda:0')}
{'acc_detail': tensor([0.9474, 0.0000, 0.0769, 0.0000], device='cuda:0'),
 'f1s_detail': tensor([0.4337, 0.0000, 0.1304, 0.0000], device='cuda:0'),
 'precision_detail': tensor([0.2812, 0.0000, 0.4286, 0.0000], device='cuda:0'),
 'recall_detail': tensor([0.9474, 0.0000, 0.0769, 0.0000], device='cuda:0'),
 'rocauc_detail': tensor([0.4373, 0.4714, 0.5235, 0.4549], device='cuda:0')}
tensor([[36,  0,  2,  0],
        [19,  0,  0,  0],
        [36,  0,  3,  0],
        [37,  0,  2,  0]], device='cuda:0')


  4%|█▍                                  | 8.18749999999996/200 [01:03<38:44, 12.12s/it]

Correct: 50/135 (0.3704)
Saved new best test model: ../scb12_models/analysis/model.epoch=11.step=264.test_acc=0.3704.pt
{'acc_unweighted': tensor(0.3252, device='cuda:0'),
 'acc_weighted': tensor(0.3704, device='cuda:0'),
 'f1s_unweighted': tensor(0.2368, device='cuda:0'),
 'f1s_weighted': tensor(0.2698, device='cuda:0'),
 'rocauc': tensor(0.6294, device='cuda:0'),
 'uar': tensor(0.3252, device='cuda:0'),
 'wap': tensor(0.2122, device='cuda:0')}
{'acc_detail': tensor([0.7368, 0.0000, 0.0000, 0.5641], device='cuda:0'),
 'f1s_detail': tensor([0.5283, 0.0000, 0.0000, 0.4190], device='cuda:0'),
 'precision_detail': tensor([0.4118, 0.0000, 0.0000, 0.3333], device='cuda:0'),
 'recall_detail': tensor([0.7368, 0.0000, 0.0000, 0.5641], device='cuda:0'),
 'rocauc_detail': tensor([0.7244, 0.6919, 0.5013, 0.5999], device='cuda:0')}
tensor([[28,  0,  1,  9],
        [ 4,  0,  0, 15],
        [19,  0,  0, 20],
        [17,  0,  0, 22]], device='cuda:0')


  8%|██▌                               | 15.375000000000163/200 [01:58<37:45, 12.27s/it]

Correct: 58/135 (0.4296)
Saved new best test model: ../scb12_models/analysis/model.epoch=21.step=504.test_acc=0.4296.pt
{'acc_unweighted': tensor(0.4158, device='cuda:0'),
 'acc_weighted': tensor(0.4296, device='cuda:0'),
 'f1s_unweighted': tensor(0.4205, device='cuda:0'),
 'f1s_weighted': tensor(0.4325, device='cuda:0'),
 'rocauc': tensor(0.6594, device='cuda:0'),
 'uar': tensor(0.4158, device='cuda:0'),
 'wap': tensor(0.4540, device='cuda:0')}
{'acc_detail': tensor([0.5526, 0.3158, 0.4359, 0.3590], device='cuda:0'),
 'f1s_detail': tensor([0.5455, 0.3333, 0.3656, 0.4375], device='cuda:0'),
 'precision_detail': tensor([0.5385, 0.3529, 0.3148, 0.5600], device='cuda:0'),
 'recall_detail': tensor([0.5526, 0.3158, 0.4359, 0.3590], device='cuda:0'),
 'rocauc_detail': tensor([0.7241, 0.7627, 0.5200, 0.6306], device='cuda:0')}
tensor([[21,  0, 14,  3],
        [ 1,  6, 11,  1],
        [11,  4, 17,  7],
        [ 6,  7, 12, 14]], device='cuda:0')


 11%|███▊                              | 22.562499999999808/200 [02:52<35:49, 12.11s/it]

Correct: 49/135 (0.3630)
{'acc_unweighted': tensor(0.3193, device='cuda:0'),
 'acc_weighted': tensor(0.3630, device='cuda:0'),
 'f1s_unweighted': tensor(0.2501, device='cuda:0'),
 'f1s_weighted': tensor(0.2851, device='cuda:0'),
 'rocauc': tensor(0.6553, device='cuda:0'),
 'uar': tensor(0.3193, device='cuda:0'),
 'wap': tensor(0.3237, device='cuda:0')}
{'acc_detail': tensor([0.8158, 0.0000, 0.0769, 0.3846], device='cuda:0'),
 'f1s_detail': tensor([0.5210, 0.0000, 0.1304, 0.3488], device='cuda:0'),
 'precision_detail': tensor([0.3827, 0.0000, 0.4286, 0.3191], device='cuda:0'),
 'recall_detail': tensor([0.8158, 0.0000, 0.0769, 0.3846], device='cuda:0'),
 'rocauc_detail': tensor([0.7572, 0.7532, 0.5262, 0.5847], device='cuda:0')}
tensor([[31,  0,  1,  6],
        [ 6,  0,  1, 12],
        [22,  0,  3, 14],
        [22,  0,  2, 15]], device='cuda:0')


 15%|█████▎                              | 29.7499999999994/200 [03:47<34:26, 12.14s/it]

Correct: 55/135 (0.4074)
{'acc_unweighted': tensor(0.3564, device='cuda:0'),
 'acc_weighted': tensor(0.4074, device='cuda:0'),
 'f1s_unweighted': tensor(0.3313, device='cuda:0'),
 'f1s_weighted': tensor(0.3786, device='cuda:0'),
 'rocauc': tensor(0.6650, device='cuda:0'),
 'uar': tensor(0.3564, device='cuda:0'),
 'wap': tensor(0.3540, device='cuda:0')}
{'acc_detail': tensor([0.6053, 0.0000, 0.3590, 0.4615], device='cuda:0'),
 'f1s_detail': tensor([0.5679, 0.0000, 0.3182, 0.4390], device='cuda:0'),
 'precision_detail': tensor([0.5349, 0.0000, 0.2857, 0.4186], device='cuda:0'),
 'recall_detail': tensor([0.6053, 0.0000, 0.3590, 0.4615], device='cuda:0'),
 'rocauc_detail': tensor([0.7404, 0.7709, 0.5088, 0.6400], device='cuda:0')}
tensor([[23,  0,  7,  8],
        [ 1,  0, 14,  4],
        [12,  0, 14, 13],
        [ 7,  0, 14, 18]], device='cuda:0')


 18%|██████▍                            | 36.93749999999983/200 [04:42<33:10, 12.21s/it]

Correct: 54/135 (0.4000)
{'acc_unweighted': tensor(0.3500, device='cuda:0'),
 'acc_weighted': tensor(0.4000, device='cuda:0'),
 'f1s_unweighted': tensor(0.3215, device='cuda:0'),
 'f1s_weighted': tensor(0.3676, device='cuda:0'),
 'rocauc': tensor(0.6645, device='cuda:0'),
 'uar': tensor(0.3500, device='cuda:0'),
 'wap': tensor(0.3529, device='cuda:0')}
{'acc_detail': tensor([0.6053, 0.0000, 0.4615, 0.3333], device='cuda:0'),
 'f1s_detail': tensor([0.5287, 0.0000, 0.3750, 0.3824], device='cuda:0'),
 'precision_detail': tensor([0.4694, 0.0000, 0.3158, 0.4483], device='cuda:0'),
 'recall_detail': tensor([0.6053, 0.0000, 0.4615, 0.3333], device='cuda:0'),
 'rocauc_detail': tensor([0.7461, 0.7659, 0.5160, 0.6301], device='cuda:0')}
tensor([[23,  0, 10,  5],
        [ 1,  0, 14,  4],
        [14,  0, 18,  7],
        [11,  0, 15, 13]], device='cuda:0')


 22%|███████▋                           | 44.12500000000065/200 [05:36<31:25, 12.10s/it]

Correct: 56/135 (0.4148)
{'acc_unweighted': tensor(0.3629, device='cuda:0'),
 'acc_weighted': tensor(0.4148, device='cuda:0'),
 'f1s_unweighted': tensor(0.3256, device='cuda:0'),
 'f1s_weighted': tensor(0.3722, device='cuda:0'),
 'rocauc': tensor(0.6831, device='cuda:0'),
 'uar': tensor(0.3629, device='cuda:0'),
 'wap': tensor(0.3447, device='cuda:0')}
{'acc_detail': tensor([0.6053, 0.0000, 0.2308, 0.6154], device='cuda:0'),
 'f1s_detail': tensor([0.5542, 0.0000, 0.2535, 0.4948], device='cuda:0'),
 'precision_detail': tensor([0.5111, 0.0000, 0.2812, 0.4138], device='cuda:0'),
 'recall_detail': tensor([0.6053, 0.0000, 0.2308, 0.6154], device='cuda:0'),
 'rocauc_detail': tensor([0.7651, 0.7872, 0.5564, 0.6237], device='cuda:0')}
tensor([[23,  0,  5, 10],
        [ 1,  0, 11,  7],
        [13,  0,  9, 17],
        [ 8,  0,  7, 24]], device='cuda:0')


 26%|████████▋                         | 51.312500000001464/200 [06:31<30:33, 12.33s/it]

Correct: 55/135 (0.4074)
{'acc_unweighted': tensor(0.3566, device='cuda:0'),
 'acc_weighted': tensor(0.4074, device='cuda:0'),
 'f1s_unweighted': tensor(0.3297, device='cuda:0'),
 'f1s_weighted': tensor(0.3767, device='cuda:0'),
 'rocauc': tensor(0.6809, device='cuda:0'),
 'uar': tensor(0.3566, device='cuda:0'),
 'wap': tensor(0.3520, device='cuda:0')}
{'acc_detail': tensor([0.6316, 0.0000, 0.3846, 0.4103], device='cuda:0'),
 'f1s_detail': tensor([0.5714, 0.0000, 0.3371, 0.4103], device='cuda:0'),
 'precision_detail': tensor([0.5217, 0.0000, 0.3000, 0.4103], device='cuda:0'),
 'recall_detail': tensor([0.6316, 0.0000, 0.3846, 0.4103], device='cuda:0'),
 'rocauc_detail': tensor([0.7713, 0.7940, 0.5198, 0.6386], device='cuda:0')}
tensor([[24,  0,  5,  9],
        [ 2,  0, 15,  2],
        [12,  0, 15, 12],
        [ 8,  0, 15, 16]], device='cuda:0')


 29%|██████████▏                        | 58.50000000000228/200 [07:25<28:53, 12.25s/it]

Correct: 52/135 (0.3852)
{'acc_unweighted': tensor(0.3504, device='cuda:0'),
 'acc_weighted': tensor(0.3852, device='cuda:0'),
 'f1s_unweighted': tensor(0.3248, device='cuda:0'),
 'f1s_weighted': tensor(0.3475, device='cuda:0'),
 'rocauc': tensor(0.6644, device='cuda:0'),
 'uar': tensor(0.3504, device='cuda:0'),
 'wap': tensor(0.3775, device='cuda:0')}
{'acc_detail': tensor([0.5526, 0.1053, 0.1026, 0.6410], device='cuda:0'),
 'f1s_detail': tensor([0.5600, 0.1600, 0.1481, 0.4310], device='cuda:0'),
 'precision_detail': tensor([0.5676, 0.3333, 0.2667, 0.3247], device='cuda:0'),
 'recall_detail': tensor([0.5526, 0.1053, 0.1026, 0.6410], device='cuda:0'),
 'rocauc_detail': tensor([0.7678, 0.7722, 0.5139, 0.6039], device='cuda:0')}
tensor([[21,  0,  1, 16],
        [ 1,  2,  6, 10],
        [ 9,  0,  4, 26],
        [ 6,  4,  4, 25]], device='cuda:0')


 33%|███████████▍                       | 65.68750000000252/200 [08:20<27:14, 12.17s/it]

Correct: 60/135 (0.4444)
Saved new best test model: ../scb12_models/analysis/model.epoch=91.step=2184.test_acc=0.4444.pt
{'acc_unweighted': tensor(0.3883, device='cuda:0'),
 'acc_weighted': tensor(0.4444, device='cuda:0'),
 'f1s_unweighted': tensor(0.3512, device='cuda:0'),
 'f1s_weighted': tensor(0.4016, device='cuda:0'),
 'rocauc': tensor(0.6988, device='cuda:0'),
 'uar': tensor(0.3883, device='cuda:0'),
 'wap': tensor(0.3813, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.0000, 0.2821, 0.6923], device='cuda:0'),
 'f1s_detail': tensor([0.5714, 0.0000, 0.3143, 0.5192], device='cuda:0'),
 'precision_detail': tensor([0.5641, 0.0000, 0.3548, 0.4154], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.0000, 0.2821, 0.6923], device='cuda:0'),
 'rocauc_detail': tensor([0.7613, 0.7754, 0.5726, 0.6859], device='cuda:0')}
tensor([[22,  0,  7,  9],
        [ 1,  0,  7, 11],
        [10,  0, 11, 18],
        [ 6,  0,  6, 27]], device='cuda:0')


 36%|████████████▊                      | 72.87500000000088/200 [09:15<26:00, 12.27s/it]

Correct: 58/135 (0.4296)
{'acc_unweighted': tensor(0.3755, device='cuda:0'),
 'acc_weighted': tensor(0.4296, device='cuda:0'),
 'f1s_unweighted': tensor(0.3493, device='cuda:0'),
 'f1s_weighted': tensor(0.3995, device='cuda:0'),
 'rocauc': tensor(0.6712, device='cuda:0'),
 'uar': tensor(0.3755, device='cuda:0'),
 'wap': tensor(0.3748, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.0000, 0.4615, 0.4615], device='cuda:0'),
 'f1s_detail': tensor([0.5570, 0.0000, 0.3956, 0.4444], device='cuda:0'),
 'precision_detail': tensor([0.5366, 0.0000, 0.3462, 0.4286], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.0000, 0.4615, 0.4615], device='cuda:0'),
 'rocauc_detail': tensor([0.7526, 0.7591, 0.5171, 0.6562], device='cuda:0')}
tensor([[22,  0,  7,  9],
        [ 1,  0, 13,  5],
        [11,  0, 18, 10],
        [ 7,  0, 14, 18]], device='cuda:0')


 40%|██████████████                     | 80.06249999999925/200 [10:09<24:54, 12.46s/it]

Correct: 63/135 (0.4667)
Saved new best test model: ../scb12_models/analysis/model.epoch=111.step=2664.test_acc=0.4667.pt
{'acc_unweighted': tensor(0.4074, device='cuda:0'),
 'acc_weighted': tensor(0.4667, device='cuda:0'),
 'f1s_unweighted': tensor(0.3749, device='cuda:0'),
 'f1s_weighted': tensor(0.4292, device='cuda:0'),
 'rocauc': tensor(0.6950, device='cuda:0'),
 'uar': tensor(0.4074, device='cuda:0'),
 'wap': tensor(0.4014, device='cuda:0')}
{'acc_detail': tensor([0.5526, 0.0000, 0.4359, 0.6410], device='cuda:0'),
 'f1s_detail': tensor([0.5316, 0.0000, 0.4359, 0.5319], device='cuda:0'),
 'precision_detail': tensor([0.5122, 0.0000, 0.4359, 0.4545], device='cuda:0'),
 'recall_detail': tensor([0.5526, 0.0000, 0.4359, 0.6410], device='cuda:0'),
 'rocauc_detail': tensor([0.7531, 0.7409, 0.5601, 0.7257], device='cuda:0')}
tensor([[21,  0,  6, 11],
        [ 2,  0,  9,  8],
        [11,  0, 17, 11],
        [ 7,  0,  7, 25]], device='cuda:0')


 44%|███████████████▎                   | 87.24999999999761/200 [11:04<23:06, 12.30s/it]

Correct: 53/135 (0.3926)
{'acc_unweighted': tensor(0.3424, device='cuda:0'),
 'acc_weighted': tensor(0.3926, device='cuda:0'),
 'f1s_unweighted': tensor(0.3143, device='cuda:0'),
 'f1s_weighted': tensor(0.3594, device='cuda:0'),
 'rocauc': tensor(0.6809, device='cuda:0'),
 'uar': tensor(0.3424, device='cuda:0'),
 'wap': tensor(0.3711, device='cuda:0')}
{'acc_detail': tensor([0.4211, 0.0000, 0.2564, 0.6923], device='cuda:0'),
 'f1s_detail': tensor([0.5161, 0.0000, 0.2632, 0.4779], device='cuda:0'),
 'precision_detail': tensor([0.6667, 0.0000, 0.2703, 0.3649], device='cuda:0'),
 'recall_detail': tensor([0.4211, 0.0000, 0.2564, 0.6923], device='cuda:0'),
 'rocauc_detail': tensor([0.7743, 0.8067, 0.5238, 0.6189], device='cuda:0')}
tensor([[16,  0,  3, 19],
        [ 0,  0, 13,  6],
        [ 7,  0, 10, 22],
        [ 1,  0, 11, 27]], device='cuda:0')


 47%|████████████████▌                  | 94.43749999999598/200 [11:59<21:33, 12.25s/it]

Correct: 59/135 (0.4370)
{'acc_unweighted': tensor(0.3823, device='cuda:0'),
 'acc_weighted': tensor(0.4370, device='cuda:0'),
 'f1s_unweighted': tensor(0.3388, device='cuda:0'),
 'f1s_weighted': tensor(0.3873, device='cuda:0'),
 'rocauc': tensor(0.7032, device='cuda:0'),
 'uar': tensor(0.3823, device='cuda:0'),
 'wap': tensor(0.3757, device='cuda:0')}
{'acc_detail': tensor([0.6316, 0.0000, 0.2308, 0.6667], device='cuda:0'),
 'f1s_detail': tensor([0.5647, 0.0000, 0.2951, 0.4952], device='cuda:0'),
 'precision_detail': tensor([0.5106, 0.0000, 0.4091, 0.3939], device='cuda:0'),
 'recall_detail': tensor([0.6316, 0.0000, 0.2308, 0.6667], device='cuda:0'),
 'rocauc_detail': tensor([0.7607, 0.7868, 0.5783, 0.6872], device='cuda:0')}
tensor([[24,  0,  4, 10],
        [ 2,  0,  5, 12],
        [12,  0,  9, 18],
        [ 9,  0,  4, 26]], device='cuda:0')


 51%|█████████████████▎                | 101.62499999999434/200 [12:53<19:56, 12.16s/it]

Correct: 55/135 (0.4074)
{'acc_unweighted': tensor(0.3763, device='cuda:0'),
 'acc_weighted': tensor(0.4074, device='cuda:0'),
 'f1s_unweighted': tensor(0.3596, device='cuda:0'),
 'f1s_weighted': tensor(0.3808, device='cuda:0'),
 'rocauc': tensor(0.6916, device='cuda:0'),
 'uar': tensor(0.3763, device='cuda:0'),
 'wap': tensor(0.3923, device='cuda:0')}
{'acc_detail': tensor([0.5526, 0.1579, 0.1538, 0.6410], device='cuda:0'),
 'f1s_detail': tensor([0.5600, 0.2069, 0.2000, 0.4717], device='cuda:0'),
 'precision_detail': tensor([0.5676, 0.3000, 0.2857, 0.3731], device='cuda:0'),
 'recall_detail': tensor([0.5526, 0.1579, 0.1538, 0.6410], device='cuda:0'),
 'rocauc_detail': tensor([0.7759, 0.7754, 0.5572, 0.6581], device='cuda:0')}
tensor([[21,  0,  1, 16],
        [ 1,  3,  8,  7],
        [11,  3,  6, 19],
        [ 4,  4,  6, 25]], device='cuda:0')


 54%|██████████████████▍               | 108.81249999999271/200 [13:48<19:36, 12.90s/it]

Correct: 62/135 (0.4593)
{'acc_unweighted': tensor(0.4079, device='cuda:0'),
 'acc_weighted': tensor(0.4593, device='cuda:0'),
 'f1s_unweighted': tensor(0.3926, device='cuda:0'),
 'f1s_weighted': tensor(0.4368, device='cuda:0'),
 'rocauc': tensor(0.7049, device='cuda:0'),
 'uar': tensor(0.4079, device='cuda:0'),
 'wap': tensor(0.4376, device='cuda:0')}
{'acc_detail': tensor([0.5789, 0.0526, 0.5128, 0.4872], device='cuda:0'),
 'f1s_detail': tensor([0.5301, 0.0870, 0.4598, 0.4935], device='cuda:0'),
 'precision_detail': tensor([0.4889, 0.2500, 0.4167, 0.5000], device='cuda:0'),
 'recall_detail': tensor([0.5789, 0.0526, 0.5128, 0.4872], device='cuda:0'),
 'rocauc_detail': tensor([0.7477, 0.7532, 0.6042, 0.7147], device='cuda:0')}
tensor([[22,  1, 10,  5],
        [ 3,  1,  8,  7],
        [11,  1, 20,  7],
        [ 9,  1, 10, 19]], device='cuda:0')


 58%|███████████████████▋              | 115.99999999999108/200 [14:43<17:08, 12.24s/it]

Correct: 47/135 (0.3481)
{'acc_unweighted': tensor(0.3222, device='cuda:0'),
 'acc_weighted': tensor(0.3481, device='cuda:0'),
 'f1s_unweighted': tensor(0.3003, device='cuda:0'),
 'f1s_weighted': tensor(0.3151, device='cuda:0'),
 'rocauc': tensor(0.6556, device='cuda:0'),
 'uar': tensor(0.3222, device='cuda:0'),
 'wap': tensor(0.3992, device='cuda:0')}
{'acc_detail': tensor([0.1053, 0.1579, 0.5128, 0.5128], device='cuda:0'),
 'f1s_detail': tensor([0.1778, 0.2069, 0.4167, 0.4000], device='cuda:0'),
 'precision_detail': tensor([0.5714, 0.3000, 0.3509, 0.3279], device='cuda:0'),
 'recall_detail': tensor([0.1053, 0.1579, 0.5128, 0.5128], device='cuda:0'),
 'rocauc_detail': tensor([0.7371, 0.7759, 0.5556, 0.5537], device='cuda:0')}
tensor([[ 4,  1,  9, 24],
        [ 0,  3, 13,  3],
        [ 3,  2, 20, 14],
        [ 0,  4, 15, 20]], device='cuda:0')


 62%|████████████████████▉             | 123.18749999998944/200 [15:37<15:46, 12.32s/it]

Correct: 52/135 (0.3852)
{'acc_unweighted': tensor(0.3580, device='cuda:0'),
 'acc_weighted': tensor(0.3852, device='cuda:0'),
 'f1s_unweighted': tensor(0.3277, device='cuda:0'),
 'f1s_weighted': tensor(0.3418, device='cuda:0'),
 'rocauc': tensor(0.6752, device='cuda:0'),
 'uar': tensor(0.3580, device='cuda:0'),
 'wap': tensor(0.3863, device='cuda:0')}
{'acc_detail': tensor([0.6842, 0.1579, 0.1026, 0.4872], device='cuda:0'),
 'f1s_detail': tensor([0.5253, 0.2222, 0.1633, 0.4000], device='cuda:0'),
 'precision_detail': tensor([0.4262, 0.3750, 0.4000, 0.3393], device='cuda:0'),
 'recall_detail': tensor([0.6842, 0.1579, 0.1026, 0.4872], device='cuda:0'),
 'rocauc_detail': tensor([0.7368, 0.7405, 0.5796, 0.6440], device='cuda:0')}
tensor([[26,  0,  1, 11],
        [ 5,  3,  2,  9],
        [18,  0,  4, 17],
        [12,  5,  3, 19]], device='cuda:0')


 65%|██████████████████████▏           | 130.37499999998943/200 [16:32<14:00, 12.08s/it]

Correct: 59/135 (0.4370)
{'acc_unweighted': tensor(0.4501, device='cuda:0'),
 'acc_weighted': tensor(0.4370, device='cuda:0'),
 'f1s_unweighted': tensor(0.3880, device='cuda:0'),
 'f1s_weighted': tensor(0.3737, device='cuda:0'),
 'rocauc': tensor(0.7058, device='cuda:0'),
 'uar': tensor(0.4501, device='cuda:0'),
 'wap': tensor(0.4543, device='cuda:0')}
{'acc_detail': tensor([0.6842, 0.5263, 0.0256, 0.5641], device='cuda:0'),
 'f1s_detail': tensor([0.5591, 0.4762, 0.0488, 0.4681], device='cuda:0'),
 'precision_detail': tensor([0.4727, 0.4348, 0.5000, 0.4000], device='cuda:0'),
 'recall_detail': tensor([0.6842, 0.5263, 0.0256, 0.5641], device='cuda:0'),
 'rocauc_detail': tensor([0.7434, 0.8099, 0.6183, 0.6514], device='cuda:0')}
tensor([[26,  1,  0, 11],
        [ 1, 10,  1,  7],
        [17,  6,  1, 15],
        [11,  6,  0, 22]], device='cuda:0')


 69%|████████████████████████           | 137.5624999999927/200 [17:26<12:40, 12.19s/it]

Correct: 60/135 (0.4444)
{'acc_unweighted': tensor(0.3959, device='cuda:0'),
 'acc_weighted': tensor(0.4444, device='cuda:0'),
 'f1s_unweighted': tensor(0.3705, device='cuda:0'),
 'f1s_weighted': tensor(0.4114, device='cuda:0'),
 'rocauc': tensor(0.6897, device='cuda:0'),
 'uar': tensor(0.3959, device='cuda:0'),
 'wap': tensor(0.4153, device='cuda:0')}
{'acc_detail': tensor([0.7105, 0.0526, 0.2821, 0.5385], device='cuda:0'),
 'f1s_detail': tensor([0.5934, 0.0833, 0.3438, 0.4615], device='cuda:0'),
 'precision_detail': tensor([0.5094, 0.2000, 0.4400, 0.4038], device='cuda:0'),
 'recall_detail': tensor([0.7105, 0.0526, 0.2821, 0.5385], device='cuda:0'),
 'rocauc_detail': tensor([0.7371, 0.7595, 0.5951, 0.6669], device='cuda:0')}
tensor([[27,  0,  2,  9],
        [ 3,  1,  6,  9],
        [13,  2, 11, 13],
        [10,  2,  6, 21]], device='cuda:0')


 72%|█████████████████████████▏         | 143.7499999999955/200 [18:12<07:07,  7.60s/it]
